[package]
name = "frunk"
version = "0.1.0"
authors = ["Lloyd <lloydmeta@gmail.com>"]
description = "Frunk provides developers with a number of functional programming tools like HList, Validate, Monoid, and Semigroup."
license = "MIT"
homepage = "https://github.com/lloydmeta/frunk"

[dependencies]
