[package]
name = "frust"
version = "0.0.3"
authors = ["Lloyd <lloydmeta@gmail.com>"]
description = "Functional Programming in Rust"
license = "MIT"
homepage = "https://github.com/lloydmeta/frust"

[dependencies]
